spring:
  profiles:
    active: dev
#  redis:
#    host: localhost
#    port: 6379

logging:
  level:
    net:
      engineeringdigest:
        journalApp: DEBUG

#logging:
#  level:
#    root: ERROR

#logging:
#  level:
#    root: OFF