spring:
  data:
    mongodb:
      uri: mongodb+srv://test:Test123@cluster0.ddik82e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: suchhanda.senapati@gmail.com
    password: ftxuugsjxncenfec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /journal

weather:
  api:
    key: c380b5d33c1557c2033428f1034108b9