##spring.application.name=JournalApp
##spring.data.mongodb.host=127.0.0.1
##spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://test:Test123@cluster0.ddik82e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
##spring.data.mongodb.username=myjournaluser
##spring.data.mongodb.password=mypassword
#spring.data.mongodb.auto-index-creation=true
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
